[2020-04-16 17:02:45] [[31merror[39m] ValidationError: Bot validation failed: name: Path `name` is required.
    at new ValidationError (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2551:32)
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2373:17
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\schematype.js:1099:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-04-16 17:04:31] [[31merror[39m] ValidationError: Bot validation failed: name: Path `name` is required.
    at new ValidationError (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2551:32)
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2373:17
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\schematype.js:1099:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-04-16 17:05:16] [[31merror[39m] ValidationError: Bot validation failed: name: Path `name` is required.
    at new ValidationError (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2551:32)
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2373:17
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\schematype.js:1099:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-04-16 17:11:37] [[31merror[39m] ValidationError: Bot validation failed: name: Path `name` is required.
    at new ValidationError (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2551:32)
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2373:17
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\schematype.js:1099:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-04-16 17:14:00] [[31merror[39m] ValidationError: Bot validation failed: name: Path `name` is required.
    at new ValidationError (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2551:32)
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2373:17
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\schematype.js:1099:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-04-16 18:21:08] [[31merror[39m] Error: User is not defined
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:97:15)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at middleware (D:\server-node-workspace\final_project_server\node_modules\express-validator\src\middlewares\check.js:15:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-16 18:21:40] [[31merror[39m] ValidationError: Bot validation failed: name: Path `name` is required.
    at new ValidationError (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2551:32)
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2373:17
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\schematype.js:1099:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-04-16 18:45:39] [[31merror[39m] TypeError: createDefaultBlock is not a function
    at model.<anonymous> (D:\server-node-workspace\final_project_server\models\Group.js:30:24)
    at callMiddlewareFunction (D:\server-node-workspace\final_project_server\node_modules\kareem\index.js:482:23)
    at model.next (D:\server-node-workspace\final_project_server\node_modules\kareem\index.js:58:7)
    at _next (D:\server-node-workspace\final_project_server\node_modules\kareem\index.js:106:10)
    at D:\server-node-workspace\final_project_server\node_modules\kareem\index.js:507:38
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-04-16 20:43:54] [[31merror[39m] TypeError: Cannot read property 'accountId' of undefined
    at getAllBot (D:\server-node-workspace\final_project_server\controllers\BotController.js:8:34)
    at D:\server-node-workspace\final_project_server\middlewares\async.js:6:21
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:89:5)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at auth (D:\server-node-workspace\final_project_server\middlewares\auth.js:22:12)
[2020-04-16 20:45:01] [[31merror[39m] TypeError: Cannot read property 'accountId' of undefined
    at getAllBot (D:\server-node-workspace\final_project_server\controllers\BotController.js:8:34)
    at D:\server-node-workspace\final_project_server\middlewares\async.js:6:21
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:89:5)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at auth (D:\server-node-workspace\final_project_server\middlewares\auth.js:22:12)
[2020-04-16 20:45:32] [[31merror[39m] TypeError: Cannot read property 'accountId' of undefined
    at getAllBot (D:\server-node-workspace\final_project_server\controllers\BotController.js:8:34)
    at D:\server-node-workspace\final_project_server\middlewares\async.js:6:21
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:89:5)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at auth (D:\server-node-workspace\final_project_server\middlewares\auth.js:22:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-16 20:46:42] [[31merror[39m] TypeError: Cannot read property 'accountId' of undefined
    at getAllBot (D:\server-node-workspace\final_project_server\controllers\BotController.js:8:34)
    at D:\server-node-workspace\final_project_server\middlewares\async.js:6:21
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:89:5)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at auth (D:\server-node-workspace\final_project_server\middlewares\auth.js:22:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-16 20:47:15] [[31merror[39m] TypeError: Cannot read property 'accountId' of undefined
    at getAllBot (D:\server-node-workspace\final_project_server\controllers\BotController.js:8:34)
    at D:\server-node-workspace\final_project_server\middlewares\async.js:6:21
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:89:5)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at auth (D:\server-node-workspace\final_project_server\middlewares\auth.js:22:12)
[2020-04-16 20:47:50] [[31merror[39m] TypeError: Cannot read property 'accountId' of undefined
    at getAllBot (D:\server-node-workspace\final_project_server\controllers\BotController.js:8:34)
    at D:\server-node-workspace\final_project_server\middlewares\async.js:6:21
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:89:5)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at auth (D:\server-node-workspace\final_project_server\middlewares\auth.js:22:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-16 21:06:33] [[31merror[39m] Error: Bot is invalid
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:97:15)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at middleware (D:\server-node-workspace\final_project_server\node_modules\express-validator\src\middlewares\check.js:15:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-16 21:22:32] [[31merror[39m] TypeError: groups.populate is not a function
    at Object.getGroupOfBot (D:\server-node-workspace\final_project_server\services\group.js:19:10)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getGroup (D:\server-node-workspace\final_project_server\controllers\GroupController.js:5:18)
[2020-04-16 21:55:07] [[31merror[39m] TokenExpiredError: jwt expired
    at D:\server-node-workspace\final_project_server\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (D:\server-node-workspace\final_project_server\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (D:\server-node-workspace\final_project_server\node_modules\jsonwebtoken\verify.js:94:10)
    at Object.verifyAccessToken (D:\server-node-workspace\final_project_server\services\auth.js:24:28)
    at auth (D:\server-node-workspace\final_project_server\middlewares\auth.js:19:43)
    at D:\server-node-workspace\final_project_server\middlewares\async.js:6:21
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:281:22
    at param (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:354:14)
    at param (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:410:3)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:174:3)
[2020-04-16 21:55:28] [[31merror[39m] JsonWebTokenError: invalid token
    at Object.module.exports [as verify] (D:\server-node-workspace\final_project_server\node_modules\jsonwebtoken\verify.js:75:17)
    at Object.verifyAccessToken (D:\server-node-workspace\final_project_server\services\auth.js:24:28)
    at auth (D:\server-node-workspace\final_project_server\middlewares\auth.js:19:43)
    at D:\server-node-workspace\final_project_server\middlewares\async.js:6:21
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:281:22
    at param (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:354:14)
    at param (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:410:3)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:174:3)
    at router (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
[2020-04-17 13:37:05] [[31merror[39m] Error: Bot data is not defined
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:97:15)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at middleware (D:\server-node-workspace\final_project_server\node_modules\express-validator\src\middlewares\check.js:15:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-17 13:40:19] [[31merror[39m] TypeError: Cannot read property 'accountId' of undefined
    at addNewBot (D:\server-node-workspace\final_project_server\controllers\BotController.js:18:34)
    at D:\server-node-workspace\final_project_server\middlewares\async.js:6:21
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:102:5)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at middleware (D:\server-node-workspace\final_project_server\node_modules\express-validator\src\middlewares\check.js:15:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-17 13:43:42] [[31merror[39m] ValidationError: Bot validation failed: name: Path `name` is required.
    at new ValidationError (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2551:32)
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2373:17
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\schematype.js:1099:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-04-17 13:44:32] [[31merror[39m] ValidationError: Bot validation failed: name: Path `name` is required.
    at new ValidationError (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2551:32)
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2373:17
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\schematype.js:1099:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-04-17 13:45:47] [[31merror[39m] Error: Bot data is not defined
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:97:15)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at middleware (D:\server-node-workspace\final_project_server\node_modules\express-validator\src\middlewares\check.js:15:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-17 13:46:18] [[31merror[39m] ValidationError: Bot validation failed: name: Path `name` is required.
    at new ValidationError (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2551:32)
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2373:17
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\schematype.js:1099:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-04-17 13:47:38] [[31merror[39m] ValidationError: Bot validation failed: name: Path `name` is required.
    at new ValidationError (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2551:32)
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2373:17
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\schematype.js:1099:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-04-17 13:48:01] [[31merror[39m] ValidationError: Bot validation failed: name: Path `name` is required.
    at new ValidationError (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\error\validation.js:31:11)
    at model.Document.invalidate (D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2551:32)
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\document.js:2373:17
    at D:\server-node-workspace\final_project_server\node_modules\mongoose\lib\schematype.js:1099:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[2020-04-17 15:41:36] [[31merror[39m] TypeError: Cannot read property '0' of undefined
    at Object.getGroupOfBot (D:\server-node-workspace\final_project_server\services\group.js:25:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getGroup (D:\server-node-workspace\final_project_server\controllers\GroupController.js:5:18)
[2020-04-17 15:41:51] [[31merror[39m] TypeError: Cannot read property '0' of undefined
    at Object.getGroupOfBot (D:\server-node-workspace\final_project_server\services\group.js:25:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getGroup (D:\server-node-workspace\final_project_server\controllers\GroupController.js:5:18)
[2020-04-19 02:12:10] [[31merror[39m] Error: Name's group is invalid 
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:173:15)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at middleware (D:\server-node-workspace\final_project_server\node_modules\express-validator\src\middlewares\check.js:15:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-19 02:20:01] [[31merror[39m] TypeError: Cannot destructure property 'groupId' of 'data' as it is undefined.
    at Object.deleteGroup (D:\server-node-workspace\final_project_server\services\group.js:53:13)
    at deleteGroup (D:\server-node-workspace\final_project_server\controllers\GroupController.js:44:36)
    at D:\server-node-workspace\final_project_server\middlewares\async.js:6:21
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:178:5)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at auth (D:\server-node-workspace\final_project_server\middlewares\auth.js:23:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-19 02:21:51] [[31merror[39m] TypeError: Cannot destructure property 'groupId' of 'data' as it is undefined.
    at Object.deleteGroup (D:\server-node-workspace\final_project_server\services\group.js:53:13)
    at deleteGroup (D:\server-node-workspace\final_project_server\controllers\GroupController.js:46:36)
    at D:\server-node-workspace\final_project_server\middlewares\async.js:6:21
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:178:5)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at auth (D:\server-node-workspace\final_project_server\middlewares\auth.js:23:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-19 02:22:32] [[31merror[39m] ReferenceError: Group is not defined
    at Object.deleteBlock (D:\server-node-workspace\final_project_server\services\block.js:43:17)
    at Object.deleteGroup (D:\server-node-workspace\final_project_server\services\group.js:54:47)
    at deleteGroup (D:\server-node-workspace\final_project_server\controllers\GroupController.js:45:36)
    at D:\server-node-workspace\final_project_server\middlewares\async.js:6:21
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:178:5)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at auth (D:\server-node-workspace\final_project_server\middlewares\auth.js:23:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-19 02:24:18] [[31merror[39m] ReferenceError: Group is not defined
    at Object.deleteBlock (D:\server-node-workspace\final_project_server\services\block.js:43:17)
    at Object.deleteGroup (D:\server-node-workspace\final_project_server\services\group.js:54:47)
    at deleteGroup (D:\server-node-workspace\final_project_server\controllers\GroupController.js:45:36)
    at D:\server-node-workspace\final_project_server\middlewares\async.js:6:21
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:178:5)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at auth (D:\server-node-workspace\final_project_server\middlewares\auth.js:23:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-19 02:24:57] [[31merror[39m] ReferenceError: BotModel is not defined
    at Object.deleteBlock (D:\server-node-workspace\final_project_server\services\block.js:53:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.deleteGroup (D:\server-node-workspace\final_project_server\services\group.js:54:28)
    at async deleteGroup (D:\server-node-workspace\final_project_server\controllers\GroupController.js:45:17)
[2020-04-19 03:43:30] [[31merror[39m] ReferenceError: Group is not defined
    at Object.addBlock (D:\server-node-workspace\final_project_server\services\block.js:19:17)
    at addNewBlock (D:\server-node-workspace\final_project_server\controllers\BlockController.js:24:38)
    at D:\server-node-workspace\final_project_server\middlewares\async.js:6:21
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:176:5)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at middleware (D:\server-node-workspace\final_project_server\node_modules\express-validator\src\middlewares\check.js:15:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-19 03:45:39] [[31merror[39m] ReferenceError: Group is not defined
    at Object.addBlock (D:\server-node-workspace\final_project_server\services\block.js:21:17)
    at addNewBlock (D:\server-node-workspace\final_project_server\controllers\BlockController.js:22:38)
    at D:\server-node-workspace\final_project_server\middlewares\async.js:6:21
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:176:5)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at middleware (D:\server-node-workspace\final_project_server\node_modules\express-validator\src\middlewares\check.js:15:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-19 03:46:39] [[31merror[39m] ReferenceError: BotModel is not defined
    at Object.addBlock (D:\server-node-workspace\final_project_server\services\block.js:23:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async addNewBlock (D:\server-node-workspace\final_project_server\controllers\BlockController.js:22:19)
[2020-04-19 03:58:49] [[31merror[39m] TypeError: session.startSession is not a function
    at Object.addBlock (D:\server-node-workspace\final_project_server\services\block.js:22:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async addNewBlock (D:\server-node-workspace\final_project_server\controllers\BlockController.js:22:19)
[2020-04-19 04:04:04] [[31merror[39m] Error
[2020-04-19 04:05:13] [[31merror[39m] Error
[2020-04-19 04:05:43] [[31merror[39m] Error
[2020-04-19 04:08:26] [[31merror[39m] Error
[2020-04-19 04:12:19] [[31merror[39m] Error
[2020-04-19 04:32:21] [[31merror[39m] Error
[2020-04-19 05:12:16] [[31merror[39m] Error
[2020-04-19 05:14:55] [[31merror[39m] Error
[2020-04-19 05:29:59] [[31merror[39m] TypeError: fn is not a function
    at D:\server-node-workspace\final_project_server\middlewares\async.js:6:21
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:176:5)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at middleware (D:\server-node-workspace\final_project_server\node_modules\express-validator\src\middlewares\check.js:15:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-19 05:40:49] [[31merror[39m] Error
[2020-04-19 14:58:56] [[31merror[39m] Error
[2020-04-19 15:01:52] [[31merror[39m] TypeError: Cannot destructure property 'message' of 'req.query.message' as it is undefined.
    at D:\server-node-workspace\final_project_server\routes\zalo.js:10:15
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:335:12)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:174:3)
    at router (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:317:13)
    at D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:335:12)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:275:10)
    at SendStream.error (D:\server-node-workspace\final_project_server\node_modules\serve-static\index.js:121:7)
[2020-04-19 15:20:22] [[31merror[39m] TypeError: Cannot read property 'lowercase' of undefined
    at D:\server-node-workspace\final_project_server\routes\zalo.js:12:25
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:335:12)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:174:3)
    at router (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:317:13)
    at D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:335:12)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:275:10)
    at SendStream.error (D:\server-node-workspace\final_project_server\node_modules\serve-static\index.js:121:7)
[2020-04-19 15:20:50] [[31merror[39m] TypeError: Cannot read property 'lowercase' of undefined
    at D:\server-node-workspace\final_project_server\routes\zalo.js:13:25
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:335:12)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:174:3)
    at router (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:317:13)
    at D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:335:12)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:275:10)
    at SendStream.error (D:\server-node-workspace\final_project_server\node_modules\serve-static\index.js:121:7)
[2020-04-19 15:18:29] [[31merror[39m] ReferenceError: id is not defined
    at D:\server-node-workspace\final_project_server\routes\zalo.js:14:26
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:335:12)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:174:3)
    at router (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:317:13)
    at D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:335:12)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:275:10)
    at SendStream.error (D:\server-node-workspace\final_project_server\node_modules\serve-static\index.js:121:7)
[2020-04-20 16:37:46] [[31merror[39m] TokenExpiredError: jwt expired
    at D:\server-node-workspace\final_project_server\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (D:\server-node-workspace\final_project_server\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (D:\server-node-workspace\final_project_server\node_modules\jsonwebtoken\verify.js:94:10)
    at Object.verifyAccessToken (D:\server-node-workspace\final_project_server\services\auth.js:24:28)
    at auth (D:\server-node-workspace\final_project_server\middlewares\auth.js:19:43)
    at D:\server-node-workspace\final_project_server\middlewares\async.js:6:21
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:335:12)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:174:3)
    at router (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
[2020-04-20 16:39:23] [[31merror[39m] ReferenceError: AccountModel is not defined
    at Object.verifyAccessToken (D:\server-node-workspace\final_project_server\services\auth.js:27:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async auth (D:\server-node-workspace\final_project_server\middlewares\auth.js:19:25)
[2020-04-20 16:59:45] [[31merror[39m] Error: Bot name is required
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:171:15)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at middleware (D:\server-node-workspace\final_project_server\node_modules\express-validator\src\middlewares\check.js:15:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-21 21:41:38] [[31merror[39m] ReferenceError: id is not defined
    at D:\server-node-workspace\final_project_server\routes\zalo.js:43:26
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:335:12)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:174:3)
    at router (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:317:13)
    at D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:335:12)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:275:10)
    at SendStream.error (D:\server-node-workspace\final_project_server\node_modules\serve-static\index.js:121:7)
[2020-04-22 19:31:25] [[31merror[39m] Error
[2020-04-22 19:37:37] [[31merror[39m] TypeError: Cannot read property '_id' of undefined
    at Object.addBlock (D:\server-node-workspace\final_project_server\services\block.js:29:40)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async addNewBlock (D:\server-node-workspace\final_project_server\controllers\BlockController.js:22:19)
[2020-04-22 19:38:31] [[31merror[39m] TypeError: Cannot read property '_id' of undefined
    at Object.addBlock (D:\server-node-workspace\final_project_server\services\block.js:30:40)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async addNewBlock (D:\server-node-workspace\final_project_server\controllers\BlockController.js:22:19)
[2020-04-22 19:44:27] [[31merror[39m] ReferenceError: errorsCodes is not defined
    at Object.transferBlock (D:\server-node-workspace\final_project_server\services\block.js:76:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async transferBlock (D:\server-node-workspace\final_project_server\controllers\BlockController.js:62:17)
[2020-04-22 19:45:39] [[31merror[39m] Error
[2020-04-22 19:46:20] [[31merror[39m] Error
[2020-04-22 19:47:02] [[31merror[39m] Error: Name's group is invalid 
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:171:15)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at middleware (D:\server-node-workspace\final_project_server\node_modules\express-validator\src\middlewares\check.js:15:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-22 19:48:12] [[31merror[39m] TypeError: Cannot read property 'exec' of undefined
    at Object.getBlock (D:\server-node-workspace\final_project_server\services\block.js:12:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getContentBlock (D:\server-node-workspace\final_project_server\controllers\BlockController.js:10:19)
[2020-04-22 19:48:58] [[31merror[39m] TypeError: BlockModel.findOne(...).populated is not a function
    at Object.getBlock (D:\server-node-workspace\final_project_server\services\block.js:11:10)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getContentBlock (D:\server-node-workspace\final_project_server\controllers\BlockController.js:10:19)
[2020-04-22 20:03:37] [[31merror[39m] Error
[2020-04-22 20:04:42] [[31merror[39m] Error
[2020-04-22 20:05:19] [[31merror[39m] Error
[2020-04-22 20:05:50] [[31merror[39m] Error: Bot name is required
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:171:15)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at middleware (D:\server-node-workspace\final_project_server\node_modules\express-validator\src\middlewares\check.js:15:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-22 20:06:03] [[31merror[39m] Error
[2020-04-23 07:39:39] [[31merror[39m] TokenExpiredError: jwt expired
    at D:\server-node-workspace\final_project_server\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (D:\server-node-workspace\final_project_server\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (D:\server-node-workspace\final_project_server\node_modules\jsonwebtoken\verify.js:94:10)
    at Object.verifyAccessToken (D:\server-node-workspace\final_project_server\services\auth.js:24:28)
    at auth (D:\server-node-workspace\final_project_server\middlewares\auth.js:19:43)
    at D:\server-node-workspace\final_project_server\middlewares\async.js:6:21
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:281:22
    at param (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:354:14)
    at param (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:410:3)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:174:3)
[2020-04-23 07:41:49] [[31merror[39m] TypeError: GroupModel.find(...).populate(...).execPopulate is not a function
    at Object.getGroupOfBot (D:\server-node-workspace\final_project_server\services\group.js:23:10)
    at getGroup (D:\server-node-workspace\final_project_server\controllers\GroupController.js:6:37)
    at D:\server-node-workspace\final_project_server\middlewares\async.js:6:21
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:176:5)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at middleware (D:\server-node-workspace\final_project_server\node_modules\express-validator\src\middlewares\check.js:15:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-23 07:42:24] [[31merror[39m] TypeError: GroupModel.findOne(...).populate(...).execPopulate is not a function
    at Object.getGroupOfBot (D:\server-node-workspace\final_project_server\services\group.js:23:10)
    at getGroup (D:\server-node-workspace\final_project_server\controllers\GroupController.js:6:37)
    at D:\server-node-workspace\final_project_server\middlewares\async.js:6:21
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at getValidationResult (D:\server-node-workspace\final_project_server\common\validation.js:176:5)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at middleware (D:\server-node-workspace\final_project_server\node_modules\express-validator\src\middlewares\check.js:15:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-23 10:03:41] [[31merror[39m] ReferenceError: options is not defined
    at D:\server-node-workspace\final_project_server\routes\zalo.js:85:22
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:335:12)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:174:3)
    at router (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:317:13)
    at D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:335:12)
    at next (D:\server-node-workspace\final_project_server\node_modules\express\lib\router\index.js:275:10)
    at SendStream.error (D:\server-node-workspace\final_project_server\node_modules\serve-static\index.js:121:7)
